name: Doxygen Deployment

on:
  release:
    types: [published]

jobs:
  doxygen_generation:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Doxygen
        uses: mattnotmitt/doxygen-action@edge
        with:
          doxyfile-path: ".github/Doxyfile"

      - name: Create redirect for root
        run: |
          mkdir -p redirect
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=${{ github.event.release.tag_name }}/"/></head></html>' > redirect/index.html

      - name: Deploy Doxygen page
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
          destination_dir: ${{ github.event.release.tag_name }}
          keep_files: true

      - name: Deploy redirect to root
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: redirect
          keep_files: true
