name: Rolling Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  rolling_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: llama_ros llama_bt
          coverage-result: false
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
